routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register'=>false]);


/*Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->name('social.login')->where('provider', 'facebook|google');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->where('provider', 'facebook|google')->name('socialCallback');*/

Route::group(['middleware'=>'guest'], function(){
	Route::get('metrics/{id?}', 'ShopifyController@createLogin');
});

Route::get('shopify/access', 'ShopifyController@shopifyInstall')->name('shopify.integrate');
Route::get('shopify/callback', 'ShopifyController@shopifyCallback')->name('shopify.callback');
Route::get('start', 'ShopifyController@loginFromStore');

Route::get('/', 'HomeController@index')->middleware('guest')->name('landing');

Route::group(['middleware'=>'auth'], function(){
	Route::get('change-password', function(){
		return view('pages.change-password');
	})->name('profile.showChangeForm');
	Route::post('change-password', 'UserController@changePassword')->name('profile.changepassword');

	/* Shopify Complete profile */
	Route::get('complete-profile', 'ShopifyController@completeProfileForm')->name('complete-profile-form');
	Route::post('complete-profile', 'ShopifyController@completeProfile')->name('complete-profile');

	/* Shopify Billing */
	Route::get('complete-payment', 'ShopifyController@shopifySubscribeForm')->name('shopify.subscibe-form');
	Route::post('do-subscribe', 'ShopifyController@shopifyDoSubscribe')->name('shopify.do-subscribe');
	Route::get('shopify/billed/{id}', 'ShopifyController@shopifySubscribed')->name('shopify.subscribed');
});

Route::group(['middleware'=>['auth', 'shopifysubscribed']], function(){
	/* Overview */
	Route::get('dashboard', 'HomeController@dashboard')->middleware('socialaccess')->name('home');
	Route::get('export-data', 'HomeController@exportXls')->name('exportxls');
	
	/* Analytics */
	Route::get('analytics', 'AnalyticsController@index')->name('analytics.index');
	Route::get('analytics-data', 'AnalyticsController@getAnalytics')->name('analytics.fetch');

	/* Products */
	Route::get('product-data', 'ProductController@index')->name('products.index');
	Route::get('products/{id}', 'ProductController@details')->name('products.details');
	Route::post('products/update-cogs', 'ProductController@updateProduct')->name('products.updateprod');
	Route::post('products/update-variants', 'ProductController@updateVariant')->name('products.updatevars');
	
	/* Social Access management */
	Route::get('manage-social-access', 'AdAccountController@index')->middleware('socialaccess')->name('adaccounts.index');
	Route::post('update-social-access', 'AdAccountController@updateAccess')->name('adaccounts.updateaccess');
	Route::get('google/callback', 'AdAccountController@googleCallback')->name('access.googlecallback');
	Route::get('social/remove/{type?}', 'AdAccountController@removeAccount')->name('access.remove');

	/* Settings */
	Route::get('settings', 'CommonController@preferences')->name('settings.index');
	Route::post('update-settings', 'CommonController@savePreferences')->name('settings.update');

	/* Expenses */	
	Route::get('expenses', 'CommonController@expenses')->name('expenses');
	Route::post('save-expenses', 'CommonController@saveExpenses')->name('saveExpenses');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $guarded = ['id'];

    public function variants(){
    	return $this->hasMany('App\Models\ProductVariant');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\ModelNotFoundException;

use App\Models\Product;
use App\Models\ProductVariant;

use Auth;

class ProductController extends Controller
{
    public function index(){
        $title = 'Products';
        $products = Product::where('user_id', Auth::id())->withCount('variants')->orderBy('product_name')->get();

        $currency = !is_null(Auth::user()->shopify_token) ? Auth::user()->shopify_token['shop_currency'] : '';

        return view('pages.products.list', compact('products', 'currency', 'title'));
    }

    public function details($id){
    	try {
    		$product = Product::where(['product_id'=>$id, 'user_id'=>Auth::id()])->with('variants')->firstOrFail();
            $currency = !is_null(Auth::user()->shopify_token) ? Auth::user()->shopify_token['shop_currency'] : '';

            return view('pages.products.details', compact('product', 'currency'));

    	} catch (ModelNotFoundException $e) {
    		abort(404);
    	}
    }

    public function updateProduct(Request $request){
        $product = Product::where(['product_id'=>$request->id, 'user_id'=>Auth::id()])->first();
        if($product){
            $product->handling_fee = $request->handling ?? 0; 
            $product->base_price = $request->base ?? 0; 
            $product->save();
            
            return response()->json(['status'=>200, 'message'=>'Product updated successfully']);
        }else{
            return response()->json(['status'=>404, 'message'=>'Product not found']);
        }
    }

    public function updateVariant(Request $request){
    	$variant = ProductVariant::where('variant_id', $request->id)->whereHas('product', function($query){
    		$query->where('user_id', Auth::id());
    	})->first();

    	if($variant){
    		$variant->handling_fee = $request->handling ?? 0; 
            $variant->base_price = $request->base ?? 0; 
            $variant->save();	
    	}

    	return true;
    }
}

resources/views/pages/products/details.blade.php
@extends('layouts.app')

@section('title_bar')
    <div class="subtitlebar">
        <h3 class="col-xs-8 col-sm-8">Product Details</h3>
    </div>
@endsection

@section('content')
    <div class="table-responsive">
        <table class="display table table-striped table-bordered variant-table" id="variants">
            <thead>
              <tr>
                <th>Variant ID</th>
                <th>Name</th>
                <th>Handling Fee ({{ $currency }})</th>
                <th>COGS ({{ $currency }})</th>
                <th class="tabledit-toolbar-column">Action</th>
            </tr>
            </thead>
            <tbody>
                @foreach ($product->variants as $variant)
                    <tr>
                        <td>{{ $variant->variant_id }}</td>
                        <td>{{ $variant->title }}</td>
                        <td>{{ $variant->handling_fee }}</td>
                        <td>{{ $variant->base_price }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection

@push('page_js')
    <script src="{{ asset('js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('js/responsive.bootstrap.min.js') }}"></script>  
    <script src="{{ asset('plugins/tabledit/jquery.tabledit.js') }}"></script>    
@endpush

@push('page_css')
    <link href="{{ asset('css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" />
@endpush

@push('scripts')
	<script type="text/javascript">
		$(function(){            
			$('#variants').Tabledit({
                url:"{{ route('products.updatevars') }}",
                columns: {
                    identifier: [0, 'id'],                    
                    editable: [[2, 'handling'], [3, 'base']],                    
                },
                buttons: {
                    edit: {
                        html: ''
                    },
                    save: {
                        html: ''
                    }
                },
                deleteButton:false
            });

            $('#variants').DataTable({
                columnDefs: [
                    { orderable: false, targets: 4 }
                ],
                paging: true,
                searching: true,
                ordering:  true,
                filter:true,
                pageLength :10,
                lengthMenu: [[10, 20, 50, -1], [10, 20, 50, 'All']],
                "bInfo" : false,
                dom: '<"float-left"B><"float-right"f>rt<"row"<"col-sm-6"l><"col-sm-6"p>>'
            });
            $("#variants_wrapper .float-left").append("<h5 class='table-heading'>Product Variants</h5>");
            $(".dataTables_filter input").attr("placeholder", "Search Product");
		});
	</script>
@endpush

resources/views/pages/products/info.blade.php
<div class="info-bar bdr-b-1 prdct-dtl">
    <div class="container">
       	<div class="float-left">
			<a href="{{ route('products.index') }}">
				<i class="fa fa-arrow-left"></i>
			</a>
			<div class="product-info">
				<div class="img-thumb">
					<img src="{{ $product->image_url }}" alt="{{ $product->product_name }}">
				</div>
				<div class="img-dtl">
					<h5>{{ $product->product_name }}</h5>
					<span>Product ID: </span><span>#{{ $product->product_id }}</span>
				</div>
			</div>
		</div>
		<div class="float-right">
			<span class="date">{{ $product->updated_at->format($date_time_format) }}</span>
			<span class="footnote">Last Updated</span>
		</div>
    </div>
</div>

resources/views/pages/products/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="whitebox nopad">
        <table id="product_table" class="table table-striped table-bordered nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Product Id</th>
                    <th>Variants</th>
                    <th>Handling Fee ({{ $currency }})</th>
                    <th>COGS ({{ $currency }})</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($products as $product)
                    <tr>
                        <td><a href="{{ route('products.details', $product->product_id) }}">
                            <div class="product-dtl">
                                <img src="{{ $product->image_url }}" alt="{{ $product->product_name }}"/>
                                <span>{{ $product->product_name }}</span>
                            </div>
                        </a></td>
                        <td>{{ $product->product_id }}</td>
                        <td>{{ $product->variants_count }}</td>
                        @if ($product->variants_count == 1)
                            <td>{{ $product->variants[0]->handling_fee }}</td>
                            <td>{{ $product->variants[0]->base_price }}</td>    
                        @else
                            <td> - </td>
                            <td> - </td>    
                        @endif
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div> 
@endsection

@push('page_js')
    <script src="{{ asset('js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('js/responsive.bootstrap.min.js') }}"></script>  
@endpush

@push('page_css')
    <link href="{{ asset('css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" />
@endpush

@push('scripts')
	<script type="text/javascript">
		$(function(){
			$('#product_table').DataTable( {
                //paging: false,
                //searching: false,
                // ordering:  false,
                pageLength :10,
                lengthMenu: [[10, 20, 50, -1], [10, 20, 50, 'All']],
                "bInfo" : false,
                dom: '<"float-left"B><"float-right"f>rt<"row"<"col-sm-6"l><"col-sm-6"p>>',
                responsive: true
            });
            
            $("#product_table_wrapper .float-left").append("<h2 class='table-heading'>Product Data</h2>");
            $(".dataTables_filter input").attr("placeholder", "Search Product");
		});
	</script>
@endpush